################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: defguide.msg,v 1.1 2003/05/19 12:28:10 j-devenish Exp $
     TAG : HEAD
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
Problem with screen inside table entries.
Problem with screen inside table entries.
No captions for ltxtable, yet.
The morerows attribute is not supported.
The morerows attribute is not supported.
No "en" localization of "glosslist" exists; using "en".
No "en" localization of "glosslist" exists; using "en".
DB2LaTeX: Need to process XPath match refsect1/mediaobjectco
DB2LaTeX: Need to process XPath match mediaobjectco/imageobjectco
DB2LaTeX: Need to process XPath match para/personname
DB2LaTeX: Need to process XPath match personname/firstname
DB2LaTeX: Need to process XPath match personname/surname
DB2LaTeX: Need to process XPath match refsect1/productionset
DB2LaTeX: Need to process XPath match productionset/title
DB2LaTeX: Need to process XPath match productionset/production
DB2LaTeX: Need to process XPath match production/lhs
DB2LaTeX: Need to process XPath match production/rhs
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match productionset/production
DB2LaTeX: Need to process XPath match production/lhs
DB2LaTeX: Need to process XPath match production/rhs
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match productionset/production
DB2LaTeX: Need to process XPath match production/lhs
DB2LaTeX: Need to process XPath match production/rhs
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match rhs/nonterminal
DB2LaTeX: Need to process XPath match production/constraint
DB2LaTeX: Need to process XPath match productionset/production
DB2LaTeX: Need to process XPath match production/lhs
DB2LaTeX: Need to process XPath match production/rhs
DB2LaTeX: Need to process XPath match refsect1/constraintdef
DB2LaTeX: Need to process XPath match constraintdef/title
No captions for ltxtable, yet.
The morerows attribute is not supported.
The morerows attribute is not supported.
DB2LaTeX: Processing BIBLIOGRAPHY
DB2LaTeX: Output Mode :  all
