file:///usr/local/share/xml/docbook/4.1.2/dbpoolx.mod:3487: validity error: Redefinition of element arg
		| sbr)*>
         ^
Entity: line 1: validity warning: Attribute id of element arg: already defined
 %common.attrib; 
               ^
file:///usr/local/share/xml/docbook/4.1.2/dbhierx.mod:209: validity error: Redefinition of element set
		setindex?)>
            ^
Entity: line 1: validity warning: Attribute id of element set: already defined
 %common.attrib; 
               ^
################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: test.msg,v 1.3 2003/04/21 07:29:07 j-devenish Exp $
     TAG : APRIL2003
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
RCAS mtext, ab
RCAS mtext,  versus 
RCAS mtext,  versus 
RCAS mtext,  versus 
RCAS mtext,  maps to 
