################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: test.msg,v 1.2 2003/04/21 03:45:27 j-devenish Exp $
     TAG : APRIL2003
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
The morerows attribute is not supported.
The morerows attribute is not supported.
The namest and nameend attributes are not supported.
The namest and nameend attributes are not supported.
The spanname attribute is not supported.
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
DB2LaTeX: Processing BIBLIOGRAPHY
DB2LaTeX: Output Mode :  all
DB2LaTeX: Processing BIBLIOGRAPHY - BIBLIODIV
DB2LaTeX: Processing BIBLIOGRAPHY - BIBLIODIV
