################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: all.msg,v 1.1 2003/04/21 03:47:16 j-devenish Exp $
     TAG : APRIL2003
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
DB2LaTeX: Processing BIBLIOGRAPHY
DB2LaTeX: Output Mode :  all
DB2LaTeX: Processing BIBLIOGRAPHY - BIBLIODIV
