################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: parskip.msg,v 1.1 2004/01/26 09:55:26 j-devenish Exp $
     TAG : HEAD
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas  casellas@infres.enst.fr                              
  AUTHOR : James Devenish  j-devenish@users.sf.net                              
   USING : libxslt/xsltproc
################################################################################
