#Code generated by the lab compiler version 2.1
#Module name AllRegisters
	.data
_n:	.space	4
_m:	.space	4
__newline:
	.asciiz	"\n"
	.text
	.globl main
main:	#first instruction
	li	$a1,-50
	sw	$a1,_m
	li	$a2,90
	sw	$a2,_n
	li	$v1,30
	sub	$a3,$v1,$a2
	neg	$v1,$a3
	li	$t1,100
	div	$t0,$t1,$v1
	sub	$v1,$a2,$t0
	li	$t1,80
	sub	$t0,$t1,$v1
	li	$t1,70
	sub	$v1,$t1,$t0
	li	$t1,60
	sub	$t0,$t1,$v1
	li	$t1,50
	sub	$v1,$t1,$t0
	li	$t1,40
	sub	$t0,$t1,$v1
	li	$t1,30
	sub	$v1,$t1,$t0
	li	$t1,20
	sub	$t0,$t1,$v1
	li	$t1,10
	sub	$v1,$t1,$t0
	sub	$t0,$a1,$v1
	mul	$a1,$t0,1
	neg	$v1,$a1
	add	$t0,$v1,21
	mul	$v1,$t0,10
	add	$t0,$v1,30
	add	$a1,$t0,4
	sw	$a1,_m
	move	$a0,$a1
	li	$v0,1
	syscall
	la	$a0,__newline
	li	$v0,4
	syscall
#sycall exit to end program
	li	$v0,10
	syscall
