#Code generated by the lab compiler version 2.1
#Module name CompareReverse
	.data
_x:	.space	4
__newline:
	.asciiz	"\n"
	.text
	.globl main
main:	#first instruction
	sw	$zero,_x
	lw	$a1,_x
	beq	$a1,0,L1
	b	L2
L1:
	li	$a1,2
	sw	$a1,_x
	b	L4
L2:
	li	$a1,1
	sw	$a1,_x
L4:
	lw	$a1,_x
	bge	$a1,0,L5
	b	L6
L5:
	li	$a1,34
	sw	$a1,_x
	b	L8
L6:
	li	$a1,2
	sw	$a1,_x
L8:
	lw	$a1,_x
	ble	$a1,40,L9
	b	L10
L9:
	add	$a1,$a1,200
	sw	$a1,_x
	b	L12
L10:
	li	$a1,3
	sw	$a1,_x
L12:
	lw	$a1,_x
	bgt	$a1,200,L13
	b	L14
L13:
	add	$a1,$a1,1000
	sw	$a1,_x
	b	L16
L14:
	li	$a1,4
	sw	$a1,_x
L16:
	lw	$a1,_x
	bne	$a1,0,L17
	b	L18
L17:
	add	$a1,$a1,1
	sw	$a1,_x
	b	L20
L18:
	li	$a1,5
	sw	$a1,_x
L20:
	lw	$a1,_x
	blt	$a1,2000,L21
	b	L22
L21:
	sub	$a1,$a1,1
	sw	$a1,_x
	b	L24
L22:
	li	$a1,6
	sw	$a1,_x
L24:
	lw	$a0,_x
	li	$v0,1
	syscall
	la	$a0,__newline
	li	$v0,4
	syscall
#sycall exit to end program
	li	$v0,10
	syscall
