#Code generated by the lab compiler version 2.1
#Module name RunOutOfRegisters
	.data
_c:	.space	4
_a:	.space	4
_jj:	.space	4
_result:	.space	4
_bb:	.space	4
_z:	.space	4
_y:	.space	4
_x:	.space	4
_w:	.space	4
_v:	.space	4
_u:	.space	4
_t:	.space	4
_s:	.space	4
_r:	.space	4
_q:	.space	4
_p:	.space	4
_o:	.space	4
_n:	.space	4
_m:	.space	4
_l:	.space	4
_k:	.space	4
_i:	.space	4
_h:	.space	4
_g:	.space	4
_f:	.space	4
_e:	.space	4
_d:	.space	4
__newline:
	.asciiz	"\n"
	.text
	.globl main
main:	#first instruction
	li	$a1,200
	sw	$a1,_a
	sw	$zero,_bb
	sw	$zero,_c
	li	$a2,5
	sw	$a2,_d
	sw	$zero,_e
	li	$a3,200
	sw	$a3,_f
	li	$v1,5
	sw	$v1,_g
	sw	$zero,_h
	sw	$zero,_i
	li	$t0,200
	sw	$t0,_jj
	li	$t1,5
	sw	$t1,_k
	sw	$zero,_l
	sw	$zero,_m
	li	$t2,200
	sw	$t2,_n
	li	$t3,5
	sw	$t3,_o
	sw	$zero,_p
	sw	$zero,_q
	li	$t4,200
	sw	$t4,_r
	li	$t5,5
	sw	$t5,_s
	sw	$zero,_t
	sw	$zero,_u
	li	$t6,200
	sw	$t6,_v
	li	$t7,5
	sw	$t7,_w
	sw	$zero,_x
	li	$t8,2
	sw	$t8,_y
	li	$t9,6
	sw	$t9,_z
	lw	$s1,_bb
	sub	$s0,$a1,$s1
	lw	$s1,_c
	sub	$a1,$s1,$a2
	sub	$a2,$s0,$a1
	lw	$s0,_e
	sub	$a1,$s0,$a3
	lw	$s0,_h
	sub	$a3,$v1,$s0
	sub	$v1,$a1,$a3
	sub	$a1,$a2,$v1
	lw	$a3,_i
	sub	$a2,$a3,$t0
	lw	$v1,_l
	sub	$a3,$t1,$v1
	sub	$v1,$a2,$a3
	sub	$a2,$a1,$v1
	lw	$a3,_m
	sub	$a1,$a3,$t2
	lw	$v1,_p
	sub	$a3,$t3,$v1
	sub	$v1,$a1,$a3
	sub	$a1,$a2,$v1
	lw	$a3,_q
	sub	$a2,$a3,$t4
	lw	$v1,_t
	sub	$a3,$t5,$v1
	sub	$v1,$a2,$a3
	sub	$a2,$a1,$v1
	lw	$a3,_u
	sub	$a1,$a3,$t6
	lw	$v1,_x
	sub	$a3,$t7,$v1
	sub	$v1,$a1,$a3
	sub	$a1,$a2,$v1
	sub	$a2,$t8,$t9
	sub	$a3,$a1,$a2
	sw	$a3,_result
	move	$a0,$a3
	li	$v0,1
	syscall
	la	$a0,__newline
	li	$v0,4
	syscall
#sycall exit to end program
	li	$v0,10
	syscall
