################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: article.msg,v 1.2 2003/04/26 03:26:09 j-devenish Exp $
     TAG : APRIL2003
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
Simple case:
