################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: fullblown.msg,v 1.1 2003/04/21 09:29:41 j-devenish Exp $
     TAG : APRIL2003
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
RCAS: Processing Revision History 
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
The morerows attribute is not supported.
The morerows attribute is not supported.
The namest and nameend attributes are not supported.
The namest and nameend attributes are not supported.
The spanname attribute is not supported.
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
No "en" localization of "informaltable" exists; using "en".
DB2LaTeX: Processing BIBLIOGRAPHY
DB2LaTeX: Output Mode :  all
Simple case:
Simple case:
Simple case:
