#Code generated by the lab compiler version 2.1
#Module name WhileNested
	.data
_y:	.space	4
_x:	.space	4
__newline:
	.asciiz	"\n"
	.text
	.globl main
main:	#first instruction
	sw	$zero,_x
L1:
	lw	$a1,_x
	blt	$a1,1200,L3
	b	L2
L3:
	li	$a2,60
	sw	$a2,_y
L5:
	lw	$a1,_y
	blt	$a1,100,L7
	b	L6
L7:
	add	$a1,$a1,20
	sw	$a1,_y
	b	L5
L6:
	lw	$a2,_x
	lw	$a3,_y
	add	$a1,$a2,$a3
	sw	$a1,_x
	b	L1
L2:
L9:
	lw	$a1,_x
	blt	$a1,1230,L11
	b	L10
L11:
	add	$a1,$a1,10
	sw	$a1,_x
	b	L9
L10:
	lw	$a2,_x
	add	$a1,$a2,4
	sw	$a1,_x
	move	$a0,$a1
	li	$v0,1
	syscall
	la	$a0,__newline
	li	$v0,4
	syscall
#sycall exit to end program
	li	$v0,10
	syscall
