################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: test.msg,v 1.2 2003/04/28 13:02:37 rcasellas Exp $
     TAG : HEAD
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
DB2LaTeX: Processing BIBLIOGRAPHY
DB2LaTeX: Output Mode :  all
Warning: Unable to find LaTeX mapping for 
KEYWORD:glossary
ROLE:end
