################################################################################
 XSLT stylesheets DocBook - LaTeX 2e                                            
 Reqs: LaTeX 2e installation common packages                                    
################################################################################
 RELEASE : 0.7.1
 VERSION : $Id: ltxtable.msg,v 1.1 2003/05/20 10:07:34 j-devenish Exp $
     TAG : HEAD
     WWW : http://db2latex.sourceforge.net                                      
 SUMMARY : http://www.sourceforge.net/projects/db2latex                         
  AUTHOR : Ramon Casellas   casellas@infres.enst.fr                             
  AUTHOR : James Devenish   j-devenish@users.sf.net                             
   USING : libxslt/xsltproc
################################################################################
No captions for ltxtable, yet.
Table column 'char' alignment is not supported.
Table column 'char' alignment is not supported.
Table column 'char' alignment is not supported.
The morerows attribute is not supported.
The morerows attribute is not supported.
